gatsby-config.ts, package.json, src/assets/images/checkmark_icon.svg, src/assets/images/select_tag_arrow_icon.svg, src/common/types/global/index.d.ts, src/components/card/card.module.scss, src/components/footer/footer.module.scss, src/components/form/form.module.scss, src/components/form/form.tsx, src/components/form/index.ts, src/components/header/header.module.scss, src/components/index.ts, src/pages/index.tsx, src/styles/index.scss, src/styles/pages/index.module.scss, src/styles/variables.scss, src/templates/layout/layout.module.scss
created form component
added wrapper for form on index page
added `gatsby-plugin-svgr` plugin
=> feature [1611] created form component

src/assets/images/minus_icon.svg, src/assets/images/plus_icon.svg, src/components/faq/faq.module.scss, src/components/faq/faq.tsx, src/components/faq/index.ts, src/components/header/header.module.scss, src/components/index.ts, src/pages/index.tsx, src/styles/auxiliary-classes.scss, src/styles/index.scss, src/styles/variables.scss, src/templates/layout/layout.module.scss
feature [1628] created FAQ component
=> feature [1628] created FAQ component

src/assets/images/left_arrow.svg, src/components/button/button.module.scss, src/components/button/button.tsx, src/components/footer/footer.tsx, src/components/head/head.tsx, src/components/swiper-buttons/swiper-buttons.tsx, src/content/index.ts, src/content/privacy-policy.tsx, src/helpers/index.ts, src/helpers/send-email.ts, src/pages/privacy-policy.tsx, src/styles/index.scss, src/styles/paddings.scss, src/styles/pages/privacy-policy.module.scss, src/templates/layout/layout.module.scss, src/templates/layout/layout.tsx, src/wrappers/index.ts, src/wrappers/information-block-wrapper/index.ts, src/wrappers/information-block-wrapper/information-block-wrapper.module.scss, src/wrappers/information-block-wrapper/information-block-wrapper.tsx
developed [1969] "Privacy policy" page
=> developed [1969] "Privacy policy" page

src/blocks/secure-scalable-decentralised/secure-scalable-decentralised.tsx, src/blocks/you-can-build-a-wallet/you-can-build-a-wallet.tsx, src/components/footer/footer.tsx, src/content/index.ts, src/content/privacy-policy.tsx, src/content/terms-of-use.tsx, src/content/you-can-participate.tsx, src/pages/terms-of-use.tsx, src/wrappers/information-block-wrapper/information-block-wrapper.module.scss, src/wrappers/information-block-wrapper/information-block-wrapper.tsx
developed [1970] "Terms and Conditions" page
=> developed [1970] "Terms and Conditions" page

src/components/header/header.tsx, src/components/side-menu/side-menu.tsx
fixed [2056] Menu does not close when user clicks on "Tagion" logo
=> fixed [2056] Menu does not close when user clicks on "Tagion" logo

src/blocks/you-can-participate/you-can-participate.tsx, src/components/custom-link/custom-link.tsx, src/components/introductory-block/introductory-block.module.scss, src/components/introductory-block/introductory-block.tsx, src/content/you-can-participate.tsx, src/pages/index.tsx
[1843] updated 'We Are Pioneering Money block' and changed links in 'You can participate' block
=> [1843] updated 'We Are Pioneering Money block' and changed links in 'You can participate' block

src/components/header/header.module.scss, src/components/header/header.tsx, src/content/navigation-links.tsx
fixed [2084] "Ecosystem" drop down menu breaks on macOS + Safari
=> fixed [2084] "Ecosystem" drop down menu breaks on macOS + Safari

src/components/form/form.tsx
fixed [2103] "Error occured" notification appears when user spamming requests in submit form
=> fixed [2103] "Error occured" notification appears when user spamming requests in submit form

src/blocks/index.ts, src/blocks/our-vision-and-mission/index.ts, src/blocks/our-vision-and-mission/our-vision-and-mission.module.scss, src/blocks/our-vision-and-mission/our-vision-and-mission.tsx, src/content/index.ts, src/content/our-vision-and-mission.tsx, src/pages/about.tsx, src/styles/margins.scss
[2129] developed our mission and vision block
=> [2129] developed our mission and vision block

src/components/header/header.module.scss, src/components/header/header.tsx
[2113] fixed: Page breaks when user refreshes it
=> [2113] fixed: Page breaks when user refreshes it

src/blocks/our-vision-and-mission/our-vision-and-mission.module.scss, src/components/contributor-swiper/contributor-swiper.module.scss, src/components/custom-swiper/custom-swiper.tsx
updated 'Our vision and mission' and fixed swiper for 'Meet our contributors'
=> updated 'Our vision and mission' and fixed swiper for 'Meet our contributors'

src/components/contributor-swiper-card/contributor-swiper-card.module.scss
[2208] fixed "Meet our contributors" images breaks on "About" page
=> [2208] fixed "Meet our contributors" images breaks on "About" page

src/components/contributor-swiper-card/contributor-swiper-card.module.scss, src/helpers/form-validation-schemas.ts
fixed phone number input behaviour and changed fonts for contributors swiper block
=> fixed phone number input behaviour and changed fonts for contributors swiper block

src/components/form/form.module.scss, src/components/submit-request-modal/submit-request-modal.module.scss, src/content/gradient-spots-props.ts
fixed bug with button on modal and improved gradient on page
=> fixed bug with button on modal and improved gradient on page

src/blocks/buy-earn-tagions/buy-earn-tagions.tsx
changed text for 'buy tagions' button
=> changed text for 'buy tagions' button

src/blocks/core-building/core-building.module.scss, src/components/index.ts, src/components/questions-block/index.ts, src/components/questions-block/questions-block.module.scss, src/components/questions-block/questions-block.tsx, src/content/FAQ.tsx, src/content/index.ts, src/pages/ecosystem.tsx, src/styles/auxiliary-classes.scss, src/styles/margins.scss, src/styles/pages/ecosystem.module.scss
=> [2235] developed "FAQ" block

src/blocks/ecosystem-visualization/ecosystem-visualization.module.scss, src/blocks/ecosystem-visualization/ecosystem-visualization.tsx, src/content/core-building.tsx
[2292] Blocks with text in "Ecosystem visualization" block does not disappear when scrolling down the page
=> [2292] Blocks with text in "Ecosystem visualization" block does not disappear when scrolling down the page

src/components/questions-block-generator/questions-block-generator.module.scss, src/components/questions-block/questions-block.module.scss
[2293] fixed "Padding "+" buttons problem"
=> [2293] fixed "Padding "+" buttons problem"

src/blocks/ecosystem-visualization/ecosystem-visualization.tsx, src/content/ecosystem-visualization.tsx
[2232] changed text and added border for video
=> [2232] changed text and added border for video

src/blocks/ecosystem-visualization/ecosystem-visualization.module.scss, src/blocks/ecosystem-visualization/ecosystem-visualization.tsx, src/content/ecosystem-visualization.tsx
[2232] synchronized two last videos
=> [2232] synchronized two last videos

src/blocks/index.ts, src/blocks/start-contributing/index.ts, src/blocks/start-contributing/start-contributing.module.scss, src/blocks/start-contributing/start-contributing.tsx, src/blocks/value-for-contributors/value-for-contributors.tsx, src/common/enums/external_links.ts, src/content/build-for-the-real-world-with-confidence.ts, src/content/gradient-spots-props.ts, src/content/index.ts, src/content/next-gen-financial-infrastrucure.ts, src/content/start-contributing.tsx, src/pages/community.tsx, src/styles/fonts.scss, src/styles/variables.scss
developed [2268] "Start contributing" block
changed text in blocks (according to the updated design)
=> developed [2268] "Start contributing" block

src/blocks/ecosystem-visualization/ecosystem-visualization.module.scss, src/blocks/start-contributing/start-contributing.module.scss, src/components/custom-swiper/custom-swiper.module.scss, src/components/tweets-swiper-card/tweets-swiper-card.module.scss, src/content/start-contributing.tsx, src/styles/fonts.scss
fixed: 
-When user tries to highlight only one element, all elements in "Inclusive. Elastic. Decentralised. Scalable." block are highlighted
-changed styles for bold font on community page
=> [2388] fixed: When user tries to highlight only one element, all elements in "Inclusive. Elastic. Decentralised. Scalable." block are highlighted

src/blocks/inclusive-elastic-decentralised/inclusive-elastic-decentralised.tsx, src/content/core-building.tsx, src/content/ecosystem-visualization.tsx, src/content/start-contributing.tsx, src/content/tweets.tsx, src/styles/auxiliary-classes.scss
[2355] fixed "No indentation in the text in "Start contributing and receive rewards" block"
=> [2355] fixed "No indentation in the text in "Start contributing and receive rewards" block"

src/common/enums/internal_links.ts, src/content/footer-links.ts, src/content/navigation-links.tsx
fixed "Blog" in the footer redirects user to the "Coming soong" page
=> [2393] fixed "Blog" in the footer redirects user to the "Coming soon" page

src/components/button/button.module.scss, src/components/button/button.tsx
fixed "Gradient on the "Back to Home" button stays when user back to "404" page"
=> [2421] fixed "Gradient on the "Back to Home" button stays when user back to "404" page"

gatsby-browser.tsx, src/components/button/button.module.scss
- attempt to fix scroll save behaviour
- improved button transition
=> attempt to fix scroll save behaviour

src/components/custom-link/custom-link.tsx, src/components/side-menu/side-menu.tsx
fixed 'Menu is not closed when the user taps on the same page he is already on'
=> [2432] fixed 'Menu is not closed when the user taps on the same page he is already on'

src/blocks/partner-and-use-cases/partner-and-use-cases.tsx
[2450] fixed issue whith build
=> [2450] fixed issue whith build

src/blocks/article/article.tsx, src/blocks/ecosystem-visualization/ecosystem-visualization.tsx, src/blocks/our-vision-and-mission/our-vision-and-mission.tsx, src/blocks/start-contributing/start-contributing.tsx, src/common/enums/names.ts, src/components/card/card.tsx, src/components/footer/footer.tsx, src/components/form/form.tsx, src/components/header/header.tsx, src/components/inclusive-elastic-decentralised-swiper-card/inclusive-elastic-decentralised-swiper-card.tsx, src/components/index.ts, src/components/input/input.tsx, src/components/introductory-block/introductory-block.tsx, src/components/socials-links/social-links.module.scss, src/components/socials-links/social-links.tsx, src/components/tooltip/index.ts, src/components/tooltip/tooltip.module.scss, src/components/tooltip/tooltip.tsx, src/content/social-links.ts, src/styles/fonts.scss, src/styles/variables.scss, src/wrappers/information-block-wrapper/information-block-wrapper.tsx
added tooltip to articles page, redirect message links for twitter/telegram and toastify messages
=> added tooltip to articles page, redirect message links for twitter/telegram and toastify messages

src/components/socials-links/social-links.tsx
=> fixed issue with building

src/components/socials-links/social-links.tsx
=> improved tooltip behaviour

src/components/page-description/page-description.module.scss
fixed 'Cursor does not look clickable when user hover it over articles'
=> [2548] fixed 'Cursor does not look clickable when user hover it over articles'

src/components/header/header.module.scss, src/components/header/header.tsx
fixed 'Header is outlined when user starts scrolling down the page'
=> [2557] fixed 'Header is outlined when user starts scrolling down the page'

src/blocks/articles/articles.tsx, src/components/header/header.module.scss, src/styles/variables.scss
added blur to the dropdown menu
=> [2560] added blur to the dropdown menu

src/blocks/articles/articles.tsx, src/components/header/header.module.scss, src/components/header/header.tsx, src/styles/variables.scss
aligned content of Docs dropdown in header
=> [2559] aligned content of Docs dropdown in header

src/components/custom-link/custom-link.tsx, src/components/header/header.module.scss, src/components/header/header.tsx
fixed 'The page the user is on is not highlighted in the header'
=> [2547] fixed 'The page the user is on is not highlighted in the header'

src/components/button/button.tsx, src/components/custom-link/custom-link.tsx, src/components/header/header.module.scss, src/components/header/header.tsx
fixed 'Gradient is always on the button on "Use cases" or "Partner" pages'
=> [2521] fixed 'Gradient is always on the button on "Use cases" or "Partner" pages

src/blocks/partner-and-use-cases/partner-and-use-cases.tsx, src/blocks/related-information/related-information.module.scss, src/blocks/related-information/related-information.tsx, src/components/card/card.tsx, src/pages/use-cases/{useCase.name}.tsx
fixed 'In the "Related articles" block there is a small text and no date'
=> [2563] fixed 'In the "Related articles" block there is a small text and no date'

package-lock.json, package.json, src/components/header/header.tsx, src/content/gradient-spots-props.ts
fixed 'Menu does not open on 1439px'
=> [2613] fixed 'Menu does not open on 1439px'

package-lock.json, package.json, src/components/header/header.tsx, src/content/gradient-spots-props.ts, src/wrappers/animated-gradient-wrapper/animated-gradient-wrapper.tsx
fixed 'Gradient is not displayed on the "Get Tagions" page'
=> [2672] fixed 'Gradient is not displayed on the "Get Tagions" page'

src/blocks/our-values/our-values.module.scss, src/blocks/our-values/our-values.tsx, src/blocks/our-vision-and-mission/our-vision-and-mission.module.scss, src/blocks/our-vision-and-mission/our-vision-and-mission.tsx, src/components/contributor-swiper/contributor-swiper.tsx, src/content/our-vision-and-mission.tsx, src/pages/about.tsx
[2690] text changes for About page
=> [2690] text changes for About page

src/content/core-building.tsx
=> [2690] added missing dot
